config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  
  resources :posts
  resources :properties

  get "/blog" => "posts#latest", as: :blog
  
  # admin routes
  get "/accounts" => 'admin#accounts', as: :accounts
  
  get "/dashboard" => 'dashboard#index', as: :dashboard
  get "/profile/:id" => 'dashboard#profile', as: :profile
  post "/agent/message" => "properties#email_agent", as: :email_agent
  
  # devise scope
  devise_scope :account do
    get 'accounts/sign_out' => "devise/sessions#destroy"
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'public#main'
end

app/views/layouts/nav/_admin.html.erb
<li class="nav-item">
    <%= link_to accounts_path, class: "nav-link" do %>
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
        Accounts <span class="sr-only">(current)</span>
    <% end %>
</li>
<li class="nav-item">
    <%= link_to properties_path, class: "nav-link" do %>
        <i data-feather="package"></i>
        Properties
    <% end %>
</li>
<li class="nav-item">
    <%= link_to posts_path, class:"nav-link" do %>
        <i data-feather="gift"></i>
        Blog Posts
    <% end %>
</li>
<li class="nav-item">
    <a class="nav-link" href="#">
        <i data-feather="users"></i>
        Adverts
    </a>
</li>

app/views/layouts/nav/_dashboard.html.erb
<nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
  <%= link_to "Property Finder", root_path,  class:"navbar-brand col-sm-3 col-md-2 mr-0" %>
    <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <%= link_to "Sign Out",  destroy_account_session_path, method: :delete, class:"nav-link" %>
    </li>
  </ul>
</nav>

app/views/layouts/nav/_public.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <div class="container">
    <a class="navbar-brand" href="<%= account_signed_in? ? dashboard_path : root_path %>" > Property Finder</a>
    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <% if account_signed_in? %>
                <%= link_to "Dashboard", dashboard_path, class:"nav-link" %>
              <% else %>
                <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
              <% end %>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Latest</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
              <div class="dropdown-menu" aria-labelledby="dropdown01">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>
            <li class="nav-item">
              <%= link_to "Blog", blog_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Advertising</a>
            </li>
          </ul>
            <% if account_signed_in? %>
                <%= link_to "Sign Out", destroy_account_session_path, method: :delete, class:"btn btn-secondary float-sm-right" %>
            <% else %>
              <%= link_to "Sign In", new_account_session_path, class:"btn btn-secondary float-sm-right mr-2" %>
              <%= link_to "Sign Up", new_account_registration_path, class:"btn btn-success float-sm-right mr-3" %>
            <% end %>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>

app/views/layouts/nav/_sidebar.html.erb
<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
  <div class="sidebar-sticky pt-3">
    <ul class="nav flex-column">
      <%= render "layouts/nav/#{ current_account.admin? ? 'admin' : 'user' }"%>

    </ul>

    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
      <span>Settings</span>
    </h6>
    <ul class="nav flex-column mb-2">
      <li class="nav-item">
        <%= link_to profile_path(current_account), class: "nav-link" do %>
          <i data-feather="file-text"></i>
          My Profile
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to edit_account_registration_path, class: "nav-link" do %>
          <i data-feather="settings"></i>
          Account Settings
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/nav/_user.html.erb
<li class="nav-item">
    <%= link_to dashboard_path, class: "nav-link" do %>
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
        Dashboard <span class="sr-only">(current)</span>
    <% end %>
</li>
<li class="nav-item">
<%= link_to properties_path, class: "nav-link" do %>
    <i data-feather="package"></i>
    Properties
<% end %>
</li>
<li class="nav-item">
<a class="nav-link" href="#">
    <i data-feather="gift"></i>
    Viewings
</a>
</li>
<li class="nav-item">
<a class="nav-link" href="#">
    <i data-feather="users"></i>
    Contacts
</a>
</li>