config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  
  resources :posts
  resources :properties

  get "/blog" => "posts#latest", as: :blog
  
  # admin routes
  get "/accounts" => 'admin#accounts', as: :accounts
  
  get "/dashboard" => 'dashboard#index', as: :dashboard
  get "/profile/:id" => 'dashboard#profile', as: :profile
  post "/agent/message" => "properties#email_agent", as: :email_agent
  
  # devise scope
  devise_scope :account do
    get 'accounts/sign_out' => "devise/sessions#destroy"
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'public#main'
end

app/models/property.rb
class Property < ApplicationRecord
    mount_uploader :photo, PhotoUploader

    belongs_to :account

    # set a new scope
    scope :latest, -> { order created_at: :desc }

    scope :sold, -> { where(for_sale: true, status: "sold") }
    scope :for_sale, -> { where(for_sale: true, status: "available") }
    scope :leased, -> { where(for_sale: false, status: "leased") }
    scope :for_rent, -> { where(for_sale: false, status: "available") }


end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: %i[ show edit update destroy ]
  before_action :authenticate_account!, only: [:new, :create, :destroy]
  before_action :set_sidebar, except: [:show]
  before_action :correct_account, only: [:edit, :update, :destroy]


  # GET /properties or /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1 or /properties/1.json
  def show
    @agent = @property.account
    # pass in array properties
    @agent_properties = Property.where(account_id: @agent.id).where.not(id: @property.id)
  end

  # GET /properties/new
  def new
    # @property = Property.new
    @property = current_account.properties.build
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties or /properties.json
  def create
    # @property = Property.new(property_params)
    @property = current_account.properties.build(property_params)
    @property.account_id = current_account.id


    respond_to do |format|
      if @property.save
        format.html { redirect_to property_url(@property), notice: "Property was successfully created." }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1 or /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to property_url(@property), notice: "Property was successfully updated." }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1 or /properties/1.json
  def destroy
    @property.destroy

    respond_to do |format|
      format.html { redirect_to properties_url, notice: "Property was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def email_agent
    # trigger email send
    first_name = params[:first_name]
    last_name = params[:last_name]
    email = params[:email]
    message = params[:message]

    # debugging
    logger.debug "First Name #{first_name}"
    logger.debug "last Name #{last_name}"
    logger.debug " Email #{email }"
    logger.debug "Message #{message}"
    # new contact mailer
    ContactMailer.email_agent( agent_id, first_name, last_name, email, message).deliver_now
    # response to script
    response_to do|format|
      format.json { head :no_content }
    end
  end
  

  def correct_account 
    @property = current_account.properties.find_by(id: params[:id])

    redirect_to properties_path, notice: "Not Authorized" if @properties.nil?
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    def set_sidebar
      @show_sidebar = true
    end

    # Only allow a list of trusted parameters through.
    def property_params
      params.require(:property).permit(:name, :address, :price, :rooms, :bathrooms, :parking_spaces, :for_sale, :status, :available_date, :details, :photo, :photo_cache, :account_id)
    end
end

app/helpers/properties_helper.rb
module PropertiesHelper

      # Individual property doesn't have img then this helper to set a default image
      def property_thumbnail property
        img = property.photo.present? ? property.photo.thumb.url : "placeholder.png"
        # return a image tag
        image_tag img, class: "property-thumb"
    end

    def property_thumbnail_url property
        img = property.photo.present? ? property.photo.thumb.url : "placeholder.png"
        image_tag img, class: "property-thumb"
    end

    def property_photo_url property
        # return a url instead of image tage
        property.photo.present? ? property.photo.url : asset_url("placeholder.png") 
    end
end

app/views/properties/_agent_details.html.erb
<div class="text-center border p-4 pb-4 ml-lg-4">
    <div class="mb-2">
        <%= profile_picture @agent %>
    </div>
    <h2 class="h4 m-0"><%= @agent.full_name %></h2>
    <p><%= @agent.company %></p>

    <div class="row">
        <div class="col-12">
            <button class="btn btn-block btn-info text-uppercase mb-3" id="show-tele" data-telephone="<%= @agent.telephone %>"><i class="fas fa-phone mr-2"></i><span>Call</span></button>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6 pr-1">
            <%= link_to "Profile", profile_path(@agent.id), class:"btn btn-secondary text-uppercase" %>
        </div>

        <div class="col-md-6 pl-1">
            <button class="btn btn-success text-uppercase" data-toggle="modal" data-target="contact-modal">Email</button>
        </div>
    </div>


</div>

app/views/properties/_form.html.erb
<%= form_with(model: property) do |form| %>
  <%= render "layouts/validation", item: @property %>
  <div class="form-group">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :price, "Total Price(for_sale) / Monthly Price (rental)" ,style: "display: block" %>
    <%= form.number_field :price, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :rooms, style: "display: block" %>
    <%= form.number_field :rooms, class:"form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :bathrooms, style: "display: block" %>
    <%= form.number_field :bathrooms, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :parking_spaces, style: "display: block" %>
    <%= form.number_field :parking_spaces, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :for_sale, style: "display: block" %>
    <%= form.select :for_sale, options_for_select({ "Yes" => true, "No" => false }, @property.for_sale ), class:"form-control" %>
  </div>

  <div class="form-group">
    <!-- Pass option that refers to rent property -->
    <% opts = @property.for_sale? ? { "Available" => "available", "Sold" => "sold" } : { "Available" => "available",  "Leased" => "leased" }  %>
    <%= form.label :status, style: "display: block" %>
    <%= form.select :status, options_for_select(opts, @property.status ), class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :available_date, style: "display: block" %>
    <%= form.date_field :available_date, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :details, style: "display: block" %>
    <%= form.text_area :details, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :photo %>
    <%= form.file_field :photo, class:"form-control" %>    
    <%= form.hidden_field :photo_cache %>

    <% if @property.photo.present? %>
      <%= image_tage @property.photo.thumb.url, class:"mt-4"  %>
    <% end %>

  </div>

  <!-- prepopulate it with the current Account Id -->
  <div class="form-group">
    <%= form.number_field :account_id,  id: :property_account_id,class:"form-control", value:current_account.id, type: :hidden %>
  </div>

  <div class="form-group">
    <%= form.submit "Save Property", class:"btn btn-success" %>
  </div>
<% end %>

app/views/properties/_list.html.erb
<% properties.each do |property| %>
    <div class="col-4">
        <div class="property border">
            <%= link_to property_path(property) do%>
                <div class="property-thumb" >
                    <%= link_to(property_thumbnail_url(property), property_path(property))%>
                </div>

                <div class="property-summary p-3">
                    <h3 class="h5"><%= link_to property.name,  property_path(property), class:"text-dark" %></h3>
                    <span class="mr-2 ml-1"><%= icon('fa-solid', 'bed')%></span> <%= property.rooms %>
                    <span class="mr-2 ml-1"><%= icon('fa-solid', 'bath')%></span> <%= property.bathrooms %>
                    <span class="mr-2 ml-1"><%= icon('fa-solid', 'car')%></span> <%= property.parking_spaces %>
                    
                    <p class="mt-2" ><%= property.address %></p>
                </div>
            <% end %>
        </div>
    </div>
<% end %>



            

app/views/properties/_profile_contact_details.html.erb
<div class="text-center">
    <div class="mb-2">
        <%= profile_picture agent %>
    </div>
    <h2 class="h4 m-0"><%= agent.full_name %></h2>
    <p><%= agent.company %></p>
    <div class="row justify-content-md-center">
        <div class="col-md-10">
            <button class="btn btn-block btn-info text-uppercase mb-1" id="show-tele" data-telephone="<%= agent.telephone %>"><i class="fas fa-phone mr-2"></i><span>Call</span></button>
        </div>
        <div class="col-md-10">
            <button class="btn btn-block btn-success text-uppercase" data-toggle="modal" data-target="contact-modal"><i class="fas fa-envelope mr-2"></i>Email</button>
        </div>
    </div>
</div>

app/views/properties/_property.html.erb
<div id="<%= dom_id property %>">
  <p>
    <strong>Name:</strong>
    <%= property.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= property.address %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= property.price %>
  </p>

  <p>
    <strong>Rooms:</strong>
    <%= property.rooms %>
  </p>

  <p>
    <strong>Bathrooms:</strong>
    <%= property.bathrooms %>
  </p>

</div>

app/views/properties/_send_email_modal.html.erb
<div class="modal fade" id="contact-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">New message for <%= agent.first_name %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_tag email_agent_path, id:"email-agent" do %>

          <%= hidden_field_tag :agent_id, agent.id %>

          <div class="form-group">
            <label for="message-first-name" class="col-form-label">First Name:</label>
            <%= text_field_tag :first_name, nil, class:"form-control", id:"message-first-name" %>
          </div>

          <div class="form-group">
            <label for="message-last-name" class="col-form-label">Last Name:</label>
            <%= text_field_tag :last_name, nil, class:"form-control", id:"message-last-name" %>
          </div>

          <div class="form-group">
            <label for="message-email" class="col-form-label"> Email:</label>
            <%= text_field_tag :email, nil, class:"form-control", id:"message-email" %>
          </div>

          <div class="form-group">
            <label for="message-text" class="col-form-label">Message:</label>
            <textarea class:"form-control", id:"message-text"></textarea>
          </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-success" id="send-message-to-agent" id="send-message">Send message</button>
      </div>
    </div>
  </div>
</div>

app/views/properties/edit.html.erb
<h1 class="h3">Editing property</h1>

<%= render "form", property: @property %>

<br>

<div>
  <%= link_to "Show this property", @property %> |
  <%= link_to "Back to properties", properties_path %>
</div>

app/views/properties/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="h3">Properties</h1>


<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Price</th>
      <th>Rooms</th>
      <th>Bathrooms</th>
      <th colspan=""></th>
    </tr>
  </thead>
  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.name %></td>
        <td><%= property.address %></td>  
        <td><%= property.price %></td>
        <td><%= property.rooms %></td>
        <td><%= property.bathrooms %></td>
        <td><%= link_to 'Show', property %></td>
        <td><%= link_to 'Edit', edit_property_path(property)%></td>
        <td><%= link_to 'Destroy', property, method: :delete, data: {confirm: "Are you sure?"} %></td>
       </tr>
    <% end %>
  </tbody>
</table>

<br/>

<%= link_to "New property", new_property_path %>

app/views/properties/new.html.erb
<h1 class="h3">New property</h1>

<%= render "form", property: @property %>

<br>

<div>
  <%= link_to "Back", properties_path, class:"btn btn-dark" %>
</div>

app/views/properties/show.html.erb
<div class="property-main-photo" style="background-image: url('<%= property_photo_url @property %>')">
  <div class="photo-overlay">

  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md  -8">
      <div class="row">
        <div class="col-lg-5">
          <p class="h4 mb-2"><%= @property.for_sale? ? "For Sale" : "For Rent" %></p>
          <p class="mb-2"><%= @property.address %></p>
          <p class="h2 mb-3">
            <% if @property.for_sale? %>
              <%= @property.price > 0 ? number_to_currency(@property.price, precision: 0) : "Offers Accepted" %>
            <% else %>
              <%= @property.price > 0 ? number_to_currency(@property.price, precision: 0) : "Open for inquiries" %> / month
            <% end %>
          </p>
        </div>
        <div class="col-lg-7 text-center">
          <div class="row mt-sm-3 bg-light p-3">
            <div class="col-4">
              <%= icon('fa-solid', 'bed')%>
              <span class="lead"><%= @property.rooms %><small>Rooms</small><span>
            </div>
            <div class="col-4">
              <%= icon('fa-solid', 'bath')%>
              <span class="lead"><%= @property.bathrooms %><small>Bedrooms</small><span>
            </div>
            <div class="col-4">
              <i class="fas fa-car"></i>
              <span class="lead"><%= @property.parking_spaces %><small>Parking</small><span>
            </div>
          </div>          
        </div>
      </div>
      <div class="row  border-top border-bottom mt-5 mb-5 pt-4 pb-4">
        <div class="col-6">
        <% if @property.for_sale? %>
          <strong><%= link_to "Est. Monthly Repayments of #{number_to_currency((@property.price - (@property.price * 0.1)) / 360, precision: 0) } *", "#", class:"text-success" %></strong>
        <% else %>
          <strong>Available <%= @property.available_date.strftime("%a") %>, <%= @property.available_date.day.ordinalize %> <%= @property.available_date.strftime("%b") %></strong>
        <% end %>
        </div>
        <div class="col-6 text-right">
          <!--This will point to a new page -->
          <strong><%= link_to "Can I afford this property?", "#", class:"text-success" %></strong>
        </div>
        </div>
        <div class="row">
          <div class="col">
            <p class="h3"><%= @property.name %></p>
            <p class="h5">Property Description</p>
            
            <!-- wrapper -->
            <div id="prop-details" class="">
              <%= simple_format @property.details %>
            </div>
            
            <button class="btn btn-outline-info mt-3" id="details">Show More</button>
            <%if @property.for_sale %>
              <p class="mt-5"> *This rate based on a 30year morgage, after paying an intial 10% down payment. Shorter term morgages would require a higher monthly repayment </p>
            <% end %>
          </div> 
        </div>
      </div>
      <div class="col-md-4">
          <%= render "properties/agent_details"%>

          <iframe class="ml-lg-4 mt-3" width="320" height="240" frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/place?key=AIzaSyBwOWZ_C1sw6lYJhxYk_LJJCI2uM9GW8IA&q=<%= @property.address.to_param %>" allowfullscreen ></iframe>
     </div>
    </div>
  </div>
</div>

<section id="mt-5 mb-5">
<div class="container">
    <div class="row">
      <div class="col-12">
        <p class="h2 mb-3">Other Properties By this Agent</p>
      </div>
      <%= render "properties/list", properties: @agent_properties%>
    </div>
</div>
</section>


<%= render "properties/send_email_modal", agent: @agent %>