config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  
  resources :posts
  resources :properties

  get "/blog" => "posts#latest", as: :blog
  
  # admin routes
  get "/accounts" => 'admin#accounts', as: :accounts
  
  get "/dashboard" => 'dashboard#index', as: :dashboard
  get "/profile/:id" => 'dashboard#profile', as: :profile
  post "/agent/message" => "properties#email_agent", as: :email_agent
  
  # devise scope
  devise_scope :account do
    get 'accounts/sign_out' => "devise/sessions#destroy"
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'public#main'
end

app/models/post.rb
class Post < ApplicationRecord
    mount_uploader :image, PhotoUploader

    belongs_to :account
    
    scope :active, -> { where(active: true) }

      # scope for latest blog post
    scope :latest, -> { order created_at: :desc }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_account!, only: [:new, :create]
  before_action :set_post, only: [:show, :edit, :update, :destroy ]
  # Add side bar
  before_action :can_access?, except: [:show, :latest]
  before_action :correct_account, only: [:edit, :update, :destroy]


  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  def latest
    @posts = Post.active
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = current_account.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    # @post = Post.new(post_params)
    @post = current_account.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_account
    @post = current_account.posts.find_by(id: params[:id])

    redirect_to posts_path, notice: "Not Authorized" if @post.nil? 
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    def can_access?
      @show_sidebar = true
      
      unless current_account.admin?
          redirect_to root_url and return
      end
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :url, :summary, :body, :image, :active, :account_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
    def post_thumbnail_url post
        img = post.image.present? ? post.image.thumb.url : "banner/blog.jpg"
        image_tag img, class: "property-thumb"
    end
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :url, style: "display: block" %>
    <%= form.text_field :url, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :summary, style: "display: block" %>
    <%= form.text_field :summary, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, class:"form-control" %>    
    <%= form.hidden_field :image_cache %>

    <% if @post.image.present? %>
      <%= image_tage @post.image.thumb.url, class:"mt-4"  %>
    <% end %>

  </div>
        <!-- prepopulate it with the current Account Id -->
  <div class="form-group">
    <%= form.number_field :account_id,  id: :post_account_id,class:"form-control", value:current_account.id, type: :hidden %>
  </div>

  <div class="form-group">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_list.html.erb
<% posts.each do |post| %>
    <div class="col-4">
        <div class="property border">
            <%= link_to post_path(post) do%>
                <div class="property-thumb" >
                    <%= link_to(post_thumbnail_url(post), post_path(post))%>
                </div>

                <div class="property-summary p-3">
                    <h3 class="h5"><%= link_to post.title,  post_path(post), class:"text-dark" %></h3>
                    
                    <p class="mt-2" ><%= post.summary %></p>
                </div>
            <% end %>
        </div>
    </div>
<% end %>



            

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Url:</strong>
    <%= post.url %>
  </p>

  <p>
    <strong>Summary:</strong>
    <%= post.summary %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= post.body %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= post.image %>
  </p>

  <p>
    <strong>Active:</strong>
    <%= post.active %>
  </p>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
      <%=link_to "Edit", edit_post_path(post) %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/latest.html.erb
<main role="main">
    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
        <div class="container">
          <h1 class="display-4">Latest Blog Posts</h1>
          <p>Stay up to date with the latest property new at Property Finder</p>
        </div>
    </div>
</main>
<div class="container">
    <% if @posts.empty? %>
        <p> No Posts to be displayed</p>
    <% else %>
        <% @posts.each do |post| %>
            <div class="row">
                <div class="col">
                    <h2><%= post.title %></h2>
                    <p><%= post.summary %></p>

                    <%= link_to "Read More >", post_path(post), class:"btn btn-success" %>
                    <hr/>
                </div>
            </div>
        <% end %>
    <% end %>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<main role="main" class="main-banner" id="blog-banner">
    <div class="jumbotron">
        <div class="container">
          <h1 class="display-4"><%= @post.title %></h1>
          <p class="text-muted pl-2"><em>Posted <%= time_ago_in_words @post.created_at %></em></p>
        </div>
    </div>
</main>
<div class="container">
  <%=image_tag @post.image.thumb.url, class:"float-right mb-4 ml-4" if @post.image.present? %>
  <%= simple_format @post.body %>

  <p><%= link_to "View All Latest Blog Posts", blog_path %></p>
</div>